name = "SplittableRandoms"
uuid = "8efc31e9-3fb0-4277-b18c-5a3d5d07abad"
authors = ["Miguel Biron-Lattes <miguel.biron@stat.ubc.ca>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
